### PR TITLE
ember-cli 0.2.7 addon

### PR DESCRIPTION
**Pull request by artych**
This is ember-charts converted to ember-cli addon `(ember-cli:0.2.7, ember 1.12.1)`. Hope this help Addepar team to speed up the transition.
- Source code was transformed from coffee to javascript (comments are preserved),
- Demo app was moved to `tests/dummy`,
- Some acceptance tests were added.

I didn't add grunt dependencies and didn't compile with grunt.

### CODE REVIEW

**Comment by artych** [comment]
@azirbel, please, confirm this is right place for such a PR.

**Comment by azirbel** [comment]
It's the right place, though @Dylnuge is a better point of contact for ember-charts.

**Comment by cyril-sf** [comment]
@artych Thanks for the PR!

We'll make sure to review it this upcoming week.

**Comment by jordansmith42** [comment]
@artych thanks for doing this! Sorry this took us a while to get to.

 I've gone through most of it and it looks pretty good, I've also merged it into the ember-charts repo where we eventually want the ember-cli version to live and opened a PR: https://github.com/Addepar/ember-charts/pull/100

We still need to back port a couple open PRs from coffeescript and make it work with ember 1.8/1.10/1.11, but then it should be good to go.

**Pull request closed without merging**
